name: Selenium Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ruchi123
          POSTGRES_DB: webapp_db
        ports:
          - 5434:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          if ! command -v google-chrome &> /dev/null; then
            sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
          fi
          
      - name: Run Flask server
        run: |
            nohup python report_dashboard.py > flask.log 2>&1 &
            sleep 5
            
      - name: Initialize database schema
        run: |
            PGPASSWORD=ruchi123 psql -h localhost -U postgres -p 5434 -d webapp_db -f init_db.sql
            
      - name: Start Flask App
        run: |
            nohup python app.py > flask.log 2>&1 &
            sleep 5  # Wait for server to fully start

      - name: Run Selenium Scripts (Headless)
        run: |
          python tests/test_login.py --headless
          python tests/test_feedback.py --headless
          
      - name: Print Test Summary to Console
        run: python report_dashboard.py --summary

      - name: Export DB results to CSV
        run: python export_results.py

      - name: Upload CSV Reports
        uses: actions/upload-artifact@v4
        with:
            name: selenium-test-reports
            path: |
                login_report.csv
                form_report.csv
